[package]
name = "protobuff-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
io = "0.0.2"
libp2p = "0.53.2"
libp2p-websocket = "0.43.0"
protobuf = "3.4.0"
tokio = "1.38.0"
tokio-core = "0.1.18"
tokio-tcp = "0.1.4"
ws = "0.9.2"
